Здравствуйте, а можно обратиться за помощью как к наставнику:

Делаю проект Foodgram, написал модели Recipe, Ingredient, Tag. 
В модели Recipe поле ingredients, как ManyToManyField к Ingredient через модель RecipeIngredient.
В модели RecipeIngredient определил поля:
1. recipe как FK к Recipe
2. ingredient как FK к Ingredient
3. amount поле, для количества 

Проблема у меня с написанием сериалализатора для создания рецепта

class RecipeIngredientSerializer(serializers.ModelSerializer):
    id = serializers.PrimaryKeyRelatedField(
        queryset=Ingredient.objects.all(),
        many=False
    )

    class Meta:
        model = RecipeIngredient
        fields = ('id', 'amount',)


class TagsSerializer(serializers.ModelSerializer):

    class Meta:
        model = Tag
        fields = '__all__'


class RecipeCreateSerializer(serializers.ModelSerializer):
    ingredients = RecipeIngredientSerializer(many=True)
    tags = serializers.PrimaryKeyRelatedField(
        many=True,
        queryset=Tag.objects.all(),
    )

    class Meta:
        model = Recipe
        fields = (
            'ingredients', 'tags', 'image', 'name', 'text', 'cooking_time')

    def create(self, validated_data):
        ingredients_data = validated_data.pop('ingredients')
        tags_data = validated_data.pop('tags')
        recipe = Recipe.objects.create(**validated_data)
        for ingredient_data in ingredients_data:
            # id = ingredient_data.pop('id').pk
            # ingredient_data['ingredient'] = Ingredient.objects.get(pk=id)
            RecipeIngredient.objects.create(recipe=recipe, **ingredient_data)
        for tag_data in tags_data:
            RecipeTag.objects.create(recipe=recipe, tag=tag_data)
        return recipe
		
Выскакивает ошибка:
TypeError: Field 'id' expected a number but got <Ingredient: облепиховый сироп>.

Ругается RecipeIngredient.objects.create(recipe=recipe, **ingredient_data)

То есть у меня здесь есть валидные данные, это:

validated_data = {'ingredients': [{'id': <Ingredient: облепиховый сироп>, 'amount': 10}], 'tags': [<Tag: завтрак>, <Tag: обед>], 'name': 'string', 'text': 'string', 'cooking_time': 1, 'author': <MyUser: kesttupest>}


Если разкомментировать 
            id = ingredient_data.pop('id').pk
            ingredient_data['ingredient'] = Ingredient.objects.get(pk=id)

То выскакивает такая ошибка:
AttributeError: Got AttributeError when attempting to get a value for field `amount` on serializer `RecipeIngredientSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Ingredient` instance.
Original exception text was: 'Ingredient' object has no attribute 'amount'.

Не пойму, как идет запрос, что вызывает эту ошибку? И как нужно правильно написать этот сериализатор?
